[package]
name = "rattler_index"

[package.build.backend]
name = "pixi-build-rust"
channels = ["https://prefix.dev/conda-forge"]

[package.target.linux.build-dependencies]
cmake = ">=3,<4"
make = ">=4,<5"
