[package]
name = "rattler_index"
version = "0.24.10"

[package.build.backend]
name = "pixi-build-rust"
version = "0.3.*"
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge"
]
