use pyo3::create_exception;
use pyo3::exceptions::PyException;

create_exception!(exceptions, InvalidVersionError, PyException);
create_exception!(exceptions, InvalidVersionSpecError, PyException);
create_exception!(exceptions, InvalidMatchSpecError, PyException);
create_exception!(exceptions, InvalidPackageNameError, PyException);
create_exception!(exceptions, PackageNameMatcherParseError, PyException);
create_exception!(exceptions, InvalidUrlError, PyException);
create_exception!(exceptions, InvalidChannelError, PyException);
create_exception!(exceptions, ActivationError, PyException);
create_exception!(exceptions, ParsePlatformError, PyException);
create_exception!(exceptions, ParseArchError, PyException);
create_exception!(exceptions, FetchRepoDataError, PyException);
create_exception!(exceptions, CacheDirError, PyException);
create_exception!(exceptions, DetectVirtualPackageError, PyException);
create_exception!(exceptions, IoError, PyException);
create_exception!(exceptions, SolverError, PyException);
create_exception!(exceptions, TransactionError, PyException);
create_exception!(exceptions, LinkError, PyException);
create_exception!(exceptions, ConvertSubdirError, PyException);
create_exception!(exceptions, VersionBumpError, PyException);
create_exception!(exceptions, VersionExtendError, PyException);
create_exception!(exceptions, ParseCondaLockError, PyException);
create_exception!(exceptions, ConversionError, PyException);
create_exception!(exceptions, RequirementError, PyException);
create_exception!(exceptions, EnvironmentCreationError, PyException);
create_exception!(exceptions, ExtractError, PyException);
create_exception!(exceptions, ActivationScriptFormatError, PyException);
create_exception!(exceptions, GatewayError, PyException);
create_exception!(exceptions, InstallerError, PyException);
create_exception!(exceptions, ParseExplicitEnvironmentSpecError, PyException);
create_exception!(exceptions, ValidatePackageRecordsError, PyException);
create_exception!(exceptions, AuthenticationStorageError, PyException);
create_exception!(exceptions, ShellError, PyException);
create_exception!(exceptions, InvalidHeaderNameError, PyException);
create_exception!(exceptions, InvalidHeaderValueError, PyException);
