package:
  name: rattler-test-package
  version: 0.1.0

build:
  noarch: generic
  string: ${{ build_string }}
  script:
    - echo "This is a test package for rattler attestation workflow"

about:
  summary: A test package for demonstrating rattler build and upload with attestation
  license: BSD-3-Clause
