[package]
name = "rattler"
version = "0.1.0"

[package.build.backend]
name = "pixi-build-rust"
version = "0.3.*"
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge"
]
