name: CI

on:
  pull_request:
    paths:
      - 'crates/rattler_networking/src/mirror_middleware.rs'
      - 'crates/rattler_networking/src/lib.rs'
      - 'crates/rattler_networking/Cargo.toml'

jobs:
  wasm-test:
    name: Test WASM Implementation
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.title, 'wasm') || contains(github.event.pull_request.body, 'wasm')
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - name: Build WASM
        run: cargo build --target wasm32-unknown-unknown -p rattler_networking
      - name: Test WASM
        run: cargo test --target wasm32-unknown-unknown -p rattler_networking 