name: JS bindings CI

on:
  push:
    branches: [main]
  pull_request:
    paths:
      # When we change pyproject.toml, we want to ensure that the maturin builds still work
      - test-data/**
      - crates/**
      - Cargo.*

      # When something in the bindings themselves changes
      - "js-rattler/**/*"

      # Or when this workflow changes
      - ".github/workflows/js-bindings.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  RUST_LOG: info
  RUST_BACKTRACE: 1
  RUSTFLAGS: "-D warnings --cfg getrandom_backend=\"wasm_js\""

jobs:
  format_lint_test:
    name: Format, Lint and Test the JS bindings
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: prefix-dev/setup-pixi@82d477f15f3a381dbcc8adc1206ce643fe110fb7 # v0.9.3
        with:
          manifest-path: js-rattler/pixi.toml

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          workspaces: js-rattler
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run rustfmt
        working-directory: js-rattler
        run: pixi run cargo fmt --all --check

      - name: Run clippy
        working-directory: js-rattler
        run: pixi run cargo clippy --all-targets

      - name: Check formatting
        working-directory: js-rattler
        run: pixi run fmt-check

      - name: Build and test
        working-directory: js-rattler
        run: pixi run test

      # some e2e test to make sure our build works
      - run: |
          set -euxo pipefail

          node ./e2e/main.cjs
          node ./e2e/main.mjs
        working-directory: js-rattler
