[package]
name = "simple_spawn_blocking"
version = "1.1.0"
description = "A simple crate to make spawning blocking tasks more ergonomic"
categories.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true


[dependencies]
tokio = { version = "1", default-features = false, features = ["rt"], optional = true }
